export const users = [
  {
    name: "Lara Vieira",
    email: "laravieira@elasporelas.com",
    telephone: "7199999-8888",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Jardinagem",
    profile_image: "profile.jpg",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Meu nome é Lara Vieira, e sou jardineira com mais de 2 anos de experiência no ramo, ofereço um serviço personalizado e de alta qualidade para atender às necessidades de cada cliente.  Se você está procurando por uma profissional confiável, atenciosa e comprometida com a qualidade, entre em contato comigo.",
    cep: "12345-678",
    street: "Rua das Flores",
    number: "123",
    Neighborhood: "Lourdes",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    feedbacks: [
      {
        username: "Cida Andrade",
        message:
          "Ótima profissional, trocou minha fechadura comum por uma eletrônica em poucas horas. Muito simpática e profissional.",
      },
    ],
    grade: 4.5,
  },
  {
    name: "Carla Pires",
    email: "carlapires@elasporelas.com",
    telephone: "7199999-1111",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Alvenaria",
    profile_image: "src/img/alvenaria/carla_pires.png",
    images: ["", ""],
    about:
      "Olá! Me chamo Carla Pires e sou especialista em serviços de alvenaria. Tenho ampla experiência na construção e reparação de estruturas. Estou comprometida em oferecer um trabalho de qualidade e duradouro. Entre em contato comigo para suas necessidades de alvenaria.",
    cep: "54321-876",
    street: "Avenida dos Construtores",
    number: "456",
    Neighborhood: "Centro",
    city: "São Paulo",
    state: "São Paulo",
    feedbacks: [
      {
        username: "Pedro Souza",
        message:
          "A Carla Pires fez um excelente trabalho na reforma da minha parede. Ficou perfeita! Recomendo seus serviços.",
      },
    ],
    grade: 4.8,
  },
  {
    name: "Celia Souza",
    email: "zeliasouza@elasporelas.com",
    telephone: "7199999-2222",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Pintura",
    profile_image: "src/img/pintura/celia_souza.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Oi! Meu nome é Celia Souza e sou especializada em serviços de pintura. Com minha habilidade e atenção aos detalhes, garanto um acabamento impecável em todos os projetos. Entre em contato comigo para transformar sua casa com uma nova pintura.",
    cep: "67890-123",
    street: "Rua das Cores",
    number: "789",
    Neighborhood: "Centro",
    city: "Rio de Janeiro",
    state: "Rio de Janeiro",
    feedbacks: [
      {
        username: "Carolina Oliveira",
        message:
          "A Celia Souza pintou meu apartamento e ficou incrível! Ela é muito profissional e cuidadosa. Recomendo!",
      },
    ],
    grade: 4.9,
  },
  {
    name: "Isabela Costa",
    email: "isabelacosta@elasporelas.com",
    telephone: "7199999-3333",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Chaveira",
    profile_image: "profile.jpg",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Meu nome é Isabela Costa e sou chaveira profissional. Posso ajudar com qualquer problema relacionado a chaves e fechaduras. Tenho experiência em instalação, reparo e troca de fechaduras. Entre em contato comigo para serviços de chaveiro confiáveis e eficientes.",
    cep: "23456-789",
    street: "Avenida das Chaves",
    number: "987",
    Neighborhood: "Barra",
    city: "Salvador",
    state: "Bahia",
    feedbacks: [
      {
        username: "Lucas Oliveira",
        message:
          "A Isabela resolveu meu problema com a fechadura rapidamente. Excelente serviço!",
      },
    ],
    grade: 4.7,
  },
  {
    name: "Lorena Freitas",
    email: "lorenafreitas@elasporelas.com",
    telephone: "7199999-4444",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Elétrica",
    profile_image: "src/img/eletrica/lorena_freitas.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Sou a Lorena Freitas e trabalho com serviços elétricos. Tenho experiência em instalações elétricas, reparos e manutenção. Garanto um serviço seguro e de qualidade. Entre em contato comigo para resolver qualquer problema elétrico em sua residência.",
    cep: "34567-890",
    street: "Rua dos Eletricistas",
    number: "654",
    Neighborhood: "Centro",
    city: "Porto Alegre",
    state: "Rio Grande do Sul",
    feedbacks: [
      {
        username: "Gabriel Ferreira",
        message:
          "A Lorena Freitas fez a instalação elétrica do meu apartamento e ficou perfeita. Recomendo!",
      },
    ],
    grade: 4.6,
  },
  {
    name: "Fran Almeida",
    email: "franalmeida@elasporelas.com",
    telephone: "7199999-5555",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Hidráulica",
    profile_image: "src/img/hidraulica/fran_almeida.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Me chamo Fran Almeida e sou especializada em serviços hidráulicos. Tenho experiência em reparos de encanamentos, instalação de chuveiros, torneiras e outros. Entre em contato comigo para solucionar problemas hidráulicos em sua casa.",
    cep: "45678-901",
    street: "Avenida das Águas",
    number: "321",
    Neighborhood: "Jardins",
    city: "Curitiba",
    state: "Paraná",
    feedbacks: [
      {
        username: "Fernanda Oliveira",
        message:
          "A Fran Almeida consertou uma infiltração no meu banheiro. Ótimo trabalho!",
      },
    ],
    grade: 4.9,
  },
  {
    name: "Roberta Costa",
    email: "robertacosta@elasporelas.com",
    telephone: "7199999-7777",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Alvenaria",
    profile_image: "src/img/alvenaria/roberta_costa.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Me chamo Roberta Costa e sou especialista em serviços de alvenaria. Tenho ampla experiência na construção e reparação de estruturas. Estou comprometida em oferecer um trabalho de qualidade e duradouro. Entre em contato comigo para suas necessidades de alvenaria.",
    cep: "12345-678",
    street: "Rua das Flores",
    number: "123",
    Neighborhood: "Lourdes",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    feedbacks: [
      {
        username: "Cida Andrade",
        message:
          "A Roberta Costa fez um excelente trabalho na reforma da minha parede. Ficou perfeita! Recomendo seus serviços.",
      },
    ],
    grade: 4.5,
  },
  {
    name: "Paloma Castro",
    email: "palomacastro@elasporelas.com",
    telephone: "7199999-8888",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Pintura",
    profile_image: "src/img/pintura/paloma_castro.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Oi! Meu nome é Paloma Castro e sou especializada em serviços de pintura. Com minha habilidade e atenção aos detalhes, garanto um acabamento impecável em todos os projetos. Entre em contato comigo para transformar sua casa com uma nova pintura.",
    cep: "54321-876",
    street: "Avenida dos Pintores",
    number: "456",
    Neighborhood: "Centro",
    city: "São Paulo",
    state: "São Paulo",
    feedbacks: [
      {
        username: "Pedro Souza",
        message:
          "A Paloma Castro pintou meu apartamento e ficou incrível! Ela é muito profissional e cuidadosa. Recomendo!",
      },
    ],
    grade: 4.8,
  },
  {
    name: "Daniela Torres",
    email: "danielatorres@elasporelas.com",
    telephone: "7199999-9999",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Chaveira",
    profile_image: "src/img/chaveiro/daniela_torres.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Meu nome é Daniela Torres e sou chaveira profissional. Posso ajudar com qualquer problema relacionado a chaves e fechaduras. Tenho experiência em instalação, reparo e troca de fechaduras. Entre em contato comigo para serviços de chaveiro confiáveis e eficientes.",
    cep: "23456-789",
    street: "Avenida das Chaves",
    number: "987",
    Neighborhood: "Barra",
    city: "Salvador",
    state: "Bahia",
    feedbacks: [
      {
        username: "Lucas Oliveira",
        message:
          "A Daniela Torres resolveu meu problema com a fechadura rapidamente. Excelente serviço!",
      },
    ],
    grade: 4.7,
  },
  {
    name: "Denise Pereira",
    email: "denisepereira@elasporelas.com",
    telephone: "7199999-1010",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Elétrica",
    profile_image: "src/img/eletrica/denise_pereira.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Sou a Denise Pereira e trabalho com serviços elétricos. Tenho experiência em instalações elétricas, reparos e manutenção. Garanto um serviço seguro e de qualidade. Entre em contato comigo para resolver qualquer problema elétrico em sua residência.",
    cep: "34567-890",
    street: "Rua dos Eletricistas",
    number: "654",
    Neighborhood: "Centro",
    city: "Porto Alegre",
    state: "Rio Grande do Sul",
    feedbacks: [
      {
        username: "Gabriel Ferreira",
        message:
          "A Denise Pereira fez a instalação elétrica do meu apartamento e ficou perfeita. Recomendo!",
      },
    ],
    grade: 4.6,
  },
  {
    name: "Tamires Oliveira",
    email: "tamiresoliveira@elasporelas.com",
    telephone: "7199999-1111",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Hidráulica",
    profile_image: "src/img/hidraulica/tamires_oliveira.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Me chamo Tamires Oliveira e sou especializada em serviços hidráulicos. Tenho experiência em reparos de encanamentos, instalação de chuveiros, torneiras e outros. Entre em contato comigo para solucionar problemas hidráulicos em sua casa.",
    cep: "45678-901",
    street: "Avenida das Águas",
    number: "321",
    Neighborhood: "Jardins",
    city: "Curitiba",
    state: "Paraná",
    feedbacks: [
      {
        username: "Fernanda Oliveira",
        message:
          "A Tamires Oliveira consertou uma infiltração no meu banheiro. Ótimo trabalho!",
      },
    ],
    grade: 4.9,
  },
  {
    name: "Letícia Lima",
    email: "leticialima@elasporelas.com",
    telephone: "7199999-1212",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Gesso",
    profile_image: "src/img/gesso/leticia_lima.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Sou a Letícia Lima e trabalho com serviços de gesso. Faço forros, sancas, molduras e muito mais. Tenho habilidade e experiência para deixar sua casa linda. Entre em contato comigo para serviços de gesso de alta qualidade.",
    cep: "56789-012",
    street: "Rua do Gesso",
    number: "123",
    Neighborhood: "Centro",
    city: "Fortaleza",
    state: "Ceará",
    feedbacks: [
      {
        username: "Luiza Oliveira",
        message:
          "A Letícia Lima fez um lindo trabalho de gesso na minha sala. Recomendo!",
      },
    ],
    grade: 4.7,
  },
  {
    name: "Gabriela Ribeiro",
    email: "gabrielaribeiro@elasporelas.com",
    telephone: "7199999-1313",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Alvenaria",
    profile_image: "profile.jpg",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Me chamo Gabriela Ribeiro e sou especialista em serviços de alvenaria. Tenho ampla experiência na construção e reparação de estruturas. Estou comprometida em oferecer um trabalho de qualidade e duradouro. Entre em contato comigo para suas necessidades de alvenaria.",
    cep: "12345-678",
    street: "Rua das Flores",
    number: "123",
    Neighborhood: "Lourdes",
    city: "Belo Horizonte",
    state: "Minas Gerais",
    feedbacks: [
      {
        username: "Cida Andrade",
        message:
          "A Gabriela fez um excelente trabalho na reforma da minha parede. Ficou perfeita! Recomendo seus serviços.",
      },
    ],
    grade: 4.5,
  },
  {
    name: "Helena Fernandes",
    email: "helenaf@gmail.com",
    telephone: "7199999-1414",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Pintura",
    profile_image: "profile.jpg",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Oi! Meu nome é Helena Fernandes e sou especializada em serviços de pintura. Com minha habilidade e atenção aos detalhes, garanto um acabamento impecável em todos os projetos. Entre em contato comigo para transformar sua casa com uma nova pintura.",
    cep: "54321-876",
    street: "Avenida dos Pintores",
    number: "456",
    Neighborhood: "Centro",
    city: "São Paulo",
    state: "São Paulo",
    feedbacks: [
      {
        username: "Pedro Souza",
        message:
          "A Helena pintou meu apartamento e ficou incrível! Ela é muito profissional e cuidadosa. Recomendo!",
      },
    ],
    grade: 4.8,
  },
  {
    name: "Kelly Ribeiro",
    email: "kellyribeiro@elasporelas.com",
    telephone: "7199999-1515",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Chaveira",
    profile_image: "src/img/chaveiro/kelly_ribeiro.jpg",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Meu nome é Kelly Ribeiro e sou chaveira profissional. Posso ajudar com qualquer problema relacionado a chaves e fechaduras. Tenho experiência em instalação, reparo e troca de fechaduras. Entre em contato comigo para serviços de chaveiro confiáveis e eficientes.",
    cep: "23456-789",
    street: "Avenida das Chaves",
    number: "987",
    Neighborhood: "Barra",
    city: "Salvador",
    state: "Bahia",
    feedbacks: [
      {
        username: "Lucas Oliveira",
        message:
          "A Kelly Ribeiro meu problema com a fechadura rapidamente. Excelente serviço!",
      },
    ],
    grade: 4.7,
  },

  {
    name: "Regina Campos",
    email: "reginacampos@elasporelas.com",
    telephone: "7199999-1818",
    password: "senha123",
    password_confirmation: "senha123",
    user_type: "profissional",
    category: "Gesso",
    profile_image: "src/img/gesso/regina_campos.png",
    images: ["portfolio1.jpg", "portfolio2.jpg"],
    about:
      "Olá! Me chamo Regina Campos e sou especializada em serviços de gesso. Realizo projetos personalizados, incluindo forros, sancas, molduras e revestimentos. Tenho experiência e dedicação em oferecer acabamentos de alta qualidade. Entre em contato comigo para transformar seu ambiente com gesso.",
    cep: "56789-012",
    street: "Rua do Gesso",
    number: "123",
    Neighborhood: "Centro",
    city: "Fortaleza",
    state: "Ceará",
    feedbacks: [
      {
        username: "Marina Oliveira",
        message:
          "A Regina Campos fez um excelente trabalho de gesso na minha sala. Ficou incrível! Recomendo!",
      },
    ],
    grade: 4.7,
  },
];
